# Generated by Django 4.0.6 on 2022-07-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(blank=True, default='uploads/default.jpg', upload_to='uploads/')),
                ('email_address', models.EmailField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('room_number', models.IntegerField()),
                ('subjects_taught', models.CharField(max_length=1000)),
            ],
        ),
    ]
